
language: node_js
node_js:
  - 20
cache:
  npm: true
  directories:
    - ~/.npm
    - react-app/node_modules
install:
  - cd react-app && npm ci
script:
  - npm run lint
  - npm run test
  - npm run build
